### ISSUE TITLE
sometimes \in is blue sometimes not

### ISSUE THREAD

**Issue by silky** [conal/paper-2021-language-derivatives#6]
on page two, for example:

![image](https://user-images.githubusercontent.com/129525/109280573-1eb7b600-7813-11eb-93e1-1f4556260567.png)

i won't list all the inconsistencies, but maybe there's a common cause.

**Comment by silky** [comment]
another example of strange colouring, page 4 (why is proj pink but inj was green? maybe this is just an agda secret i'm not yet familiar with):

![image](https://user-images.githubusercontent.com/129525/109288115-5aa34900-781c-11eb-80fc-cb4693f05810.png)

**Comment by conal** [comment]
Thanks\! I think all uses of `∈` are blue now.

> (why is `proj` pink but `inj` was green? maybe this is just an agda secret i’m not yet familiar with)

I think it’s because the `projᵢ` are field accessors while the `injᵢ` are data constructors. Agda is choosing the colors.
