### ISSUE TITLE
page 2: clarification of statement around proofs

### ISSUE THREAD

**Issue by silky** [conal/paper-2021-language-derivatives#7]
this comment:

![image](https://user-images.githubusercontent.com/129525/109280915-87069780-7813-11eb-8992-16729b47a515.png)

suggests that the proof has to provide an explanation of which of P or Q was chosen; but it's not clear to me why? couldn't P and Q even overlap, so there's no way to say which one it was? i would think that any specific detail of P or Q is erased by the type `P \union Q`? (but i'm probably misunderstanding)

i think maybe you're saying that because the proof is constructive it'll be clear where the element is found? or perhaps that you can run the proof for P and then for Q and see which one it works for?

i think most likely i'm misunderstanding something.

**Comment by conal** [comment]
> couldn’t P and Q even overlap, so there’s no way to say which one it was?

Yes, `P` and `Q` might overlap, even in the extreme of being identical. *Every* inhabitant (proof) of `(P ∪ Q) w` will give its own explanation.

> i think maybe you’re saying that because the proof is constructive it’ll be clear where the element is found?

Not *the* proof, but rather *each* proof.

**Comment by conal** [comment]
New wording:

> For instance, every proof of *w ∈ P ∪ Q* contains a proof of *w ∈ P* or of *w ∈ Q*, and the knowledge of which one was chosen (with different proofs reflecting different choices).

Better?

**Comment by silky** [comment]
sounds good! :)
