### ISSUE TITLE
page 3: missing part of footnote

### ISSUE THREAD

**Issue by silky** [conal/paper-2021-language-derivatives#9]
![image](https://user-images.githubusercontent.com/129525/109285707-4f9ae980-7819-11eb-991a-e72f677c1c6f.png)

exercise for the reader? :)

-- edit: upon reflection, the latter part of this sentence this was probably meant as a sentence that preceeds the fold definition itself.

**Comment by silky** [comment]
i now see that it isn't missing, it just appears on page 5.

see #10

**Comment by conal** [comment]
Oh, wow. I hadn't noticed that particularly bad footnote split.
